language: scala
scala:
  - 2.11.8
  - 2.10.4
jdk:
  - oraclejdk8

script:
- sbt clean coverage test package
# Trick to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm

after_success:
  - >
      sbt coveralls &&
      sh "$TRAVIS_BUILD_DIR/travis-ci-bintray-credentials.sh" &&
      sbt publish